openshwprojects/OpenBK7231T_App

src/httpclient/http_client.c, src/httpclient/http_client.h, src/httpserver/http_tcp_server.c, src/httpserver/new_http.c, src/httpserver/new_http.h, src/logging/logging.c, src/new_cfg.h, src/new_common.c, src/ota/ota.c, src/printnetinfo/printnetinfo.c, src/printnetinfo/printnetinfo.h, src/tuya_device.c
Chores that must be done.
A few warnings remain - will visit again later
=> fix some warnings

src/httpclient/http_client.c, src/httpclient/http_client.h, src/httpclient/utils_timer.c, src/httpserver/http_tcp_server.c, src/httpserver/new_http.c, src/logging/logging.c, src/new_cfg.c, src/new_common.h, src/new_pins.c, src/new_pins.h, src/ota/ota.c, src/ota/ota.h, src/printnetinfo/printnetinfo.c, src/tuya_device.c
=> All warnings eliminated, 1 bug sorted.

src/httpserver/http_tcp_server.c, src/httpserver/new_http.c, src/httpserver/new_http.h, src/new_pins.c, src/new_pins.h, src/tuya_device.c
The fix in http is to provide a callback and FD to use to send data back when it gets too big....
=> Add wifi LED (untested) + fix HTTP return from pins config

src/httpserver/http_tcp_server.c, src/httpserver/new_http.c, src/httpserver/new_http.h, src/logging/logging.c, src/tuya_device.c, src/win_main.c
The main thing this does is base everything on a http_request_t structure.
It also introduces a 'poststr(p_request, str)' for adding data to the http response, which automatically checks the available size, and really sends if it has to.
This should make it easier to create (for example) a rest style API, essential for an external web interface.
It should also avoid breaking the server by expanding the number of pin entries, etc.
Please check it over carefully.  I have built & tested in windows, but not on a real device (as I have no serial connection temporarily!).
=> Btsimonh5 - webserver updates

src/flash_config/flash_config.c, src/flash_config/flash_config.h, src/httpserver/new_http.c, src/httpserver/new_http.h, src/httpserver/rest_interface.c, src/new_cfg.c, src/new_cfg.h, src/new_common.h, src/new_pins.c, src/new_pins.h, src/ota/ota.c, src/user_main.c
comprehensive update.
bugfixes.
Take time to look at the new functions.  It's all quite heavily tested.
Also converts wifi & MQTT (although MQTT maybe not so well) to new structures.
You will need to reset pins...
=> Flash config 

src/httpserver/new_http.c, src/new_builtin_devices.c, src/new_pins.h
Modified all three files to add 2 more devices to the quick config. Tested with own build. All seems to work OK.
=> Quick Configs for Nedis devices

src/httpserver/new_http.c, src/new_builtin_devices.c, src/new_pins.h
One more Smartplug config. This device has also BL0937 Current Measurement Chip. Build Tested with my "dev-build" before making PR
=> Emax EDU8774 SmartPlug config

src/flash_config/flash_config.h, src/httpserver/new_http.c, src/httpserver/rest_interface.c, src/new_cfg.c, src/new_pins.c
minor changes just to finish freeing ourselves from the net_params in the SDK.
=> move config from SDK to app - the SDK mods can now be removed

src/httpserver/rest_interface.c
e.g. http://192.168.1.176/api/flash/1e0000-1000
reads RF setup table
add POST /api/flash/<hex addr> to WRITE anywhere after 0x132000
=> add GET /api/flash/<hexstart>-<hexend> to read any part of flash

src/httpserver/new_http.c
=> Fixed typo for BK7231T naming

src/mqtt/new_mqtt.c
the mqtt driver does not terminate data..
and nor does strncpy??????????
so... max len from mqtt now 128 bytes?
pls. check.
=> fix setting valus from mqtt

src/httpserver/new_http.c
Thanks @boozeman for reminding me! I need to get Git going for me, how to send a local change to my git repo to create it in one single PR, then this would have been included
=> Adding T version of Qiachip

.github/workflows/workflow.yaml, .gitignore, .gitmodules, .releaserc.yaml, Makefile
Use GitHub actions to automatically build and release new versions, adding binaries to release outputs (e.g. https://github.com/talltechdude/OpenBK7231T_App/releases) and also tests builds on PRs.
Uses [Conventional Commits](https://www.conventionalcommits.org/) and [cycjimmy/semantic-release-action@v2](https://github.com/cycjimmy/semantic-release-action) to automatically increment release versions and generate change logs.
Also makes use of a simplified Makefile to build assets pulling in the SDK via a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to ease development of app only inside single repo (while remaining compatible with exisiting SDK)
=> feat: automated GitHub releases

.github/workflows/workflow.yaml, Makefile
I've added a Makefile command to automatically update the SDK submodules, effectively just a git pull on each and commit the changes.
```
make update-submodules
```
Also fixed the fail-fast logic as it was cancelling other builds if any platform failed.
=> feat: update sdks from Makefile

src/httpserver/http_fns.c, src/httpserver/http_fns.h, src/httpserver/new_http.c, src/httpserver/new_http.h
=> Httprefactor

src/new_builtin_devices.c
=> Avatar led

src/httpserver/http_fns.c, src/new_builtin_devices.c, src/new_pins.h
Hi, Thanks for this great project. It saved me from replacing the MCU of my Tuya Smart Wifi Switch.
This is the template for that device. This was a quick modification and hope I didn't miss anything. I've tried it on my device and it seems to be working fine. Let me know if you want me to change anything.
Thanks.
Switch Model: DS-101JL
Module: CB3S
Board: 
A-1011CW4B2-T4-V2.0
2021-09-03
=> Add '[BK7231N][CB3S] Tuya Smart Wifi Switch 4 Gang' Template

src/httpserver/http_fns.c, src/new_builtin_devices.c
I added the LSC Smart Connect Plug  (https://www.action.com/de-at/p/lsc-smart-connect-intelligenter-stecker/) as Quick Template.
Here a Screenshot from the working config:
I think I did everything right :)
=> Added LSC Smart Connect Plug

src/httpserver/http_fns.c, src/new_builtin_devices.c, src/new_pins.h
Add Quick config for AU Deta Smart Double Power Wall outlet 6922HA series 2
=> Quick config for AU Deta Smart Double Power Wall outlet 6922HA Series 2

src/driver/drv_tuyaMCU.c
The Moes/Maxcio Rotary Dimmer model EDM-1WAA-EU (https://templates.blakadder.com/maxcio_EDM-1WAA-EU.html) uses a TuyaMCU with a baud rate of 115200, currently the rate 9600 is hard-coded and it does not work with this dimmer. So I implemented the tuyaMcu_setBaudRate command to set the rate. Similar to SetOption97 command from the Tasmota project. 
Both ON/OFF toggle and dimming work.
The autoexec.bat commands used to make the dimmer work:
startDriver TuyaMCU
tuyaMcu_setBaudRate 115200
setChannelType 1 toggle
setChannelType 2 dimmer
tuyaMcu_setDimmerRange 0 1000
linkTuyaMCUOutputToChannel 1 1 1
linkTuyaMCUOutputToChannel 2 2 2
=> Added tuyaMcu_setBaudRate command

src/httpserver/http_fns.c, src/new_builtin_devices.c, src/new_pins.h
Quick Config template for 'CasaLife CCT Downlight SMART-AL2017-TGTS'
=> feat: Quick Config template for CasaLife CCT Downlight

src/httpserver/http_fns.c, src/new_builtin_devices.c, src/new_pins.h
The device wiki is temporary/under review: https://www.elektroda.com/rtvforum/viewtopic.php?p=20133554#20133554
=> Quick config for Enbrighten WFD4103

src/httpserver/http_fns.c, src/new_builtin_devices.c, src/new_pins.h
Quick config for Sonoff MiniR3,
I posted this a couple days ago on the forums:
https://www.elektroda.com/rtvforum/topic3889041-120.html#20129679
Small correction:
WIFI LED is actually inverted so it'll stay on solid after the blinking/connecting to the wifi routine.
=> Sonoff MiniR3 quick config

src/httpserver/http_fns.c, src/new_builtin_devices.c, src/new_pins.h
- This PR add quick configuration support for Aubess Mini Smart Switch 16A.
- Device description -> #147 
- [Aliexpress Link](https://www.aliexpress.com/item/1005003631131323.html?)
=> Add quick configuration for Aubess Mini Smart Switch 16A

README.md
I've added pretty much everything of the README to the Github Wiki, so I thought why not add a Reference to it in the README.
(NOTE: Leaving it up to you what you want to fully move to the wiki and what you want to leave in the README).
=> Added WIKI Reference to README.md

README.md
Just a small change to make the README.md prettier.
=> Small Chnage for Style

src/httpserver/http_fns.c
* Updated `unique_id` based on https://developers.home-assistant.io/docs/entity_registry_index/
* Also updated on/off payload  #138
=> Generate better uniqued id, fixed payload

src/httpserver/http_fns.c
This request 
* Aligns the layout of checkbox (before the label and not underneath it)
* Makes the checkbox more accessible (label can be clicked to change the state)
Before:
New layout:
=> Improve flags config html

src/httpserver/http_fns.c, src/httpserver/new_http.c, src/httpserver/new_http.h, src/httpserver/rest_interface.c, src/logging/logging.c
First attempt to tweak some of the HTML in the UI. I'd like to update things to be a bit easier to use, potentially more consistent with Tasmota. Starting small as I figure things out in the code. 
* Made the links to repo, forum thread, donation open with target=_blank (in a new tab)
* Tweaked the UI to move all the status-information (state of devices, watchdog) together (this moves the shared UI items down a bit)
* Made it possible to just request the status information via http://URL/index?state= 
* Made the status-information section auto-updating with JavaScript every 3 seconds
First commit :)
=> Status information auto-updates, tweaked HTML

src/httpserver/http_fns.c, src/httpserver/new_http.c, src/httpserver/new_http.h, src/httpserver/rest_interface.c, src/logging/logging.c
Reverts openshwprojects/OpenBK7231T_App#177
=> Revert "Status information auto-updates, tweaked HTML"

src/cJSON/LICENSE, src/cJSON/Readme.txt, src/cJSON/cJSON.c, src/cJSON/cJSON.h, src/httpserver/hass.c, src/httpserver/hass.h
This PR is in preparation for #183 (which I will revise). This includes some new files which would be used in #183.
Here are the other associated merge requests:
* BK7231T - sdk\include\cJSON.h has been commented out to prevent build errors. https://github.com/openshwprojects/OpenBK7231T/pull/7
* W800 - this SDK had an older cJSON. The Makefile has been adjusted to include new .cs files and skip building SDK cJSON component https://github.com/openshwprojects/OpenW800/pull/2.
* XR809 - same changes as W800 https://github.com/openshwprojects/OpenXR809/pull/3
=> Added new files for 183

src/httpserver/new_http.c
=> W600 fixes

src/logging/logging.c
Just some cleaning up in the logging function
* use strncpy() instead of strcpy() 
* use vsnprintf() instead of vsprintf() 
* move static char tmp[1024]; into the individual functions for cleaner code
* filter out double /r/n in logging (strip from original if exists, add once back)
=> Add some buffer overflow protection for logging (& some cleanup) 

src/driver/drv_bl0937.c, src/driver/drv_bl_shared.c, src/driver/drv_local.h, src/driver/drv_public.h, src/httpserver/http_fns.c, src/logging/logging.c, src/new_builtin_devices.c, src/new_pins.h
Fixed logging changes, which caused freezing in OTA handler. 
BL0937 - added command for resetting energy counter
HTTP - added Quick Config for TESLA SmartPlug TSL-SPL-1 (available in Slovakia ALZA)
MQTT - BL0937 message sending changes. Implemented min 5s interval between messages. Added threshold for EnergyCounter.
=> Bug fix Logging. TESLA SmartPlug work

src/driver/drv_bp5758d.c, src/driver/drv_bp5758d.h
Reason for the bug and test can be seen in #221
=> [drv_bp5758d] Fix sleep mode (or "dim up" issue)

src/httpserver/http_fns.c, src/new_builtin_devices.c, src/new_pins.h
Add MagicHome CCT : ZJ-BWCE-CCT v1.1
=> https://www.elektroda.com/rtvforum/topic3889041.html#19999397
=> Add MagicHome CCT : ZJ-BWCE-CCT v1.1

src/cmnds/cmd_newLEDDriver.c, src/driver/drv_bp1658cj.c, src/driver/drv_bp5758d.c, src/driver/drv_tuyaMCU.c, src/httpserver/hass.c, src/httpserver/http_fns.c
* Consolidated duplicate strings/code, fixed some build warnings
* Added condiguration_url which appears here in HomeAssistant
=> Hass / removed duplicate code

src/driver/drv_bl_shared.c, src/driver/drv_bltest.c, src/driver/drv_local.h, src/driver/drv_main.c, src/driver/drv_public.h, src/httpserver/hass.c, src/httpserver/http_fns.c, src/obk_config.h
Support for voltage/current and power sensors. [#259](https://github.com/openshwprojects/OpenBK7231T_App/issues/259)
* Introduced a test driver which can be activated by setting ENABLE_BL_TEST_DRIVER in obk_config.h
* Also added `stopDriver` command
=> Hass discovery power

src/httpserver/hass.c, src/logging/logging.c
Another stability change towards logging. This change seems to resolve the hang in W600. The change is safe and reduces the continuous malloc/free operations which should help in general since we are actually logging once or more within a second.
=> Logging using static buffer

src/httpserver/http_fns.c, src/new_builtin_devices.c, src/new_pins.h
Can't build and test at the moment; pls confirm it builds?
=> Add device Calex Smart Plug 900011.1

src/hal/bk7231/hal_wifi_bk7231.c, src/hal/hal_wifi.h, src/hal/w800/hal_adc_w800.c, src/hal/w800/hal_wifi_w800.c
* Implemented home missing logging functions for W800/W600
* Fixed ADC pin definitions
* Formatted the touched files
=> More w800 600 cleanup

BUILDING.md, gulpfile.js, src/httpserver/new_http.c, src/httpserver/script.js, src/httpserver/script_ha_discovery.js, src/httpserver/style.css
* Updated Building readme
* Added comment headers to css/js files about editing
* Adjust gulp script to include space around = to match formatting and formatted it.
=> Updated readme and adjusted formattings

README.md, src/driver/drv_bl0937.c, src/driver/drv_bl0942.c, src/driver/drv_bl_shared.c, src/driver/drv_bltest.c, src/driver/drv_cse7766.c, src/driver/drv_local.h, src/driver/drv_tuyaMCU.c, src/httpserver/new_http.c
Power monitor - added configurable history model
Fixed bug: missing call of BL_stared_init
Fixed bug: htprintf128 change to use vsnprintf with buffer limit set to 256 bytes
=> Consumption measurement - configurable history

README.md, src/cmnds/cmd_test.c, src/driver/drv_bl_shared.c, src/driver/drv_main.c, src/driver/drv_public.h, src/driver/drv_tuyaMCU.c, src/httpserver/hass.c, src/httpserver/http_fns.c
HA Assistent fixes. "dev_cla" specs values changed.
TuyaMCU - added comments
=> HA Assistent fixes

src/driver/drv_ir.cpp
create new variable repeats, send with MQTT.
We may want another flag to not sent repeats on MQTT?
We may want to pass repeats to events.
=> Minor IR stuff

.gitmodules, Makefile
Force submodules to master branch and auto update them all if required (was missing some of the more recent repos)
=> fix: submodule auto-update

src/cJSON/cJSON.c, src/cmnds/cmd_channels.c, src/cmnds/cmd_newLEDDriver.c, src/driver/drv_bl0937.c, src/driver/drv_bl0942.c, src/driver/drv_bl_shared.c, src/driver/drv_cse7766.c, src/driver/drv_ir.cpp, src/driver/drv_main.c, src/driver/drv_tuyaMCU.c, src/hal/w800/hal_wifi_w800.c, src/httpclient/http_client.c, src/httpclient/utils_net.c, src/httpserver/hass.c, src/httpserver/http_fns.c, src/httpserver/new_http.c, src/httpserver/new_http.h, src/httpserver/rest_interface.c, src/mqtt/new_mqtt.c, src/new_cfg.c
replace many sprintf with snprintf.
change name of hprintf128 to hprintf255
Does not actually resolve any issues, but could protect us a little....
=> Snprintf pr

src/driver/drv_main.c, src/httpserver/hass.c
Addresses https://github.com/openshwprojects/OpenBK7231T_App/issues/329
=> Removed None

src/logging/logging.c
move mutex to BEFORE we empty the logging temp buffer.
Add option for log_delay < 0 -> delay according to number of characters logged at 115200 baud.
=> small logging tweeks

src/logging/logging.c
@openshwprojects
@btsimonh
This addresses https://github.com/openshwprojects/OpenBK7231T_App/issues/354 by reverting some of the changes from https://github.com/openshwprojects/OpenBK7231T_App/pull/344.
* A line used to be commented out in getSerial and was uncommented which results serial output flooding -- commented it back.
* Reverted and added back the `while`+ `rtos_delay_milliseconds(10);` in non-PLATFORM_BEKEN specific `og_serial_thread`. I don't understand why the loop is needed and identified this fix by reverting commits.
=> Fixed logging hang w600

src/driver/drv_main.c, src/driver/drv_ssdp.c, src/driver/drv_ssdp.h
This is NOT started by default.  run cmd "startdriver SSDP" - and you device will appear in windows networking....
We COULD in the future 'hear' notify messages from other OBK devices, so that all devices could know about each other... or even send an MSEARCH.
=> add driver SSDP. … run cmd "startdriver SSDP"

src/driver/drv_ssdp.c, src/driver/drv_ssdp.h, src/user_main.c
bugfix on my previous mod to allow multiple drivers (<4) to be scheduled to start,
Then add start of SSDP if it had previously been running....
Allows startdriver SSDP in startup to work, as driver is restarted at wifi connect.
=> Fix scheduletask

src/cmnds/cmd_if.c, src/cmnds/cmd_tokenizer.c, src/driver/drv_bl_shared.c, src/driver/drv_main.c, src/driver/drv_ntp.c, src/driver/drv_ntp.h, src/httpserver/http_fns.c, src/mqtt/new_mqtt.c, src/mqtt/new_mqtt.h, src/ota/ota.c, src/ota/ota.h
MQTT - fix for timestamp for HA discovery. Checking OTA running process, MQTT will disconnect automatically. MQTT benchmark added. 
DRV - Fix generation of last clearing date. MQTT connection check before publishing.
NTP - retab formatting. Checking OTA running process, which stops next NTP check. TZ export
OTA - minor optimization. Faster version.
Tested device N,T
Pull request for OpenBK7231T
=> MQTT, OTA changes

src/cmnds/cmd_eventHandlers.c, src/user_main.c
Delays start by 720ms -
ensuring that other startup thread have completed before we start to try to use TCP/IP.
=> Delayedstartup

src/cmnds/cmd_test.c, src/new_common.c
for testing
vsnprintf2 NOT in place
=> Add testFloats cmd

src/httpserver/http_fns.c
Made the color range look like this to match the same in Homeassistant along with some white space cleanup in generated html.
=> Added color background

src/driver/drv_ir.cpp, src/httpserver/new_http.c
allows IR tx when RX is not present.
=> IR Tx without IR RX

src/driver/drv_main.c, src/httpserver/http_fns.c, src/new_pins.h
Minor fix to not use NTP as the feature when logging driver start/stop operations.
Previously, driver action would be listed under NTP
=> Fixed logging feature

src/httpserver/hass.c
This addresses https://github.com/openshwprojects/OpenBK7231T_App/issues/444
=> Energy values should be total_increasing

src/hal/bk7231/hal_wifi_bk7231.c, src/new_pins.c
convert pin time analysis to be based on MS rather than ticks.
This SHOULD allow us to in the future run the pins from edge interrupts....
=> Pins - update to ms

src/hal/bk7231/hal_main_bk7231.c, src/mqtt/new_mqtt.c, src/mqtt/new_mqtt.h, src/new_pins.c
working MQTT based on using 
LOCK_TCPIP_CORE();
res = mqtt_client_is_connected(mqtt_client);
UNLOCK_TCPIP_CORE();
Works on N & T even with IR interrupt active
Also, queues incoming MQTT and processes them in the timer thread (on beken, else in quicktick)
=> Mqtt test2

src/cmnds/cmd_main.c, src/cmnds/cmd_public.h, src/logging/logging.c, src/user_main.c
modify startup on beken to start some things early, and some things after TCP is ready,
=> Undelayedstart

src/hal/bk7231/hal_main_bk7231.c, src/logging/logging.c
This PR changes logging on Beken.
It removes spinning threads (serial, tcp), and instead calls a log trigger function, which pends a log send function against the timer thread.
This means that log sending will only be triggered when logs are ready to be sent.
Hence we can sleep for many ms when no logs are ready to be sent.
The TCP logging allows for up to TWO connections only on the port 9000 log port.
Additional connections will fail.
But closing the connection and re-opening is fine.
Negatives:
If the device is spinning in a timer function (e.g. MQTT gethostbyname), no logs will emerge until it is finished.
Positives:
We no longer use polling to service logs, and so avoid short rtos_delays
=> Nologloops - toward power save

src/logging/logging.c
now it can only pend a single log sevrice call at a time, rather than overflowing the timer queue. A second call can be pended during the first call if the logs did not complete outputting.
the PR nologloops caused excessive logging (e.g. when MQTT blasting) to crash the device.
This resolves it.
=> bugfix logging -

src/httpserver/hass.c, src/httpserver/hass.h
Switched to using 100 for brightness level.
=> Fix discovery brightness scale

src/httpserver/http_fns.c, src/httpserver/rest_interface.c, src/ota/ota.c, src/ota/ota.h
This PR extends ota_progress() to W600.
I made the existing functions available externally to W600 SDK. Existing code's compilation was suppressed in non-BEKEN mode.
This has to be paired with matching PR in W600 - https://github.com/openshwprojects/OpenW600/pull/4
=> Updating OTA status

src/httpserver/http_fns.c
This merge will help with https://github.com/openshwprojects/OpenBK7231T_App/issues/654 but will not resolve it.
* Removes white spaces from HTML
* Adjusts redundant code/strings in some functions: http_fn_cfg_mqtt, http_fn_cfg_webapp, http_fn_cfg_quick, http_fn_ha_cfg
* Also made a couple helper functions: poststr_h2, poststr_h4 - they seemed to help a bit
http_fn_ha_cfg can be sunset in favor of automatic discovery. Details about manual definitions can be provided via a wiki.
=> Consolidated some code, removed white spaces

src/httpserver/http_fns.c
Allow clearing startup command.
=> Accept empty startup command

src/cmnds/cmd_main.c, src/driver/drv_sht3x.c, src/new_pins.c
Adding Command to control alerting mode for SHT : 
SHT_ReadAlert => to get alert configuration on SHT sensor : 
SHT_SetAlert => to configure alert mode on SHT sensor with temp low/high and Humidity low/high
SHT_ClearStatus => Who clear the alert status after a reboot. 
this commande is  really usefull in // of pin deepsleep cause SHT can wake up the BK thru dinput line if alert is reached. 
SHT Alert mode is activated only if periodical measurement is activated (thru SHT_Launchper) 
Adding correction on new_pins.c to correct pindeepsleep for bk7231N.
=> Sht alert command

src/driver/drv_battery.c, src/driver/drv_local.h, src/driver/drv_main.c, src/driver/drv_sht3x.c, src/user_main.c
Will launch on each frame a measurement.
detect automatically if periodical is activated
=> Adding RunFrame for SHT Driver.

src/driver/drv_spi.c
As I don't have hardware for testing it could work, but also could not work. Please use the code and try to fix it, if it is not working.
The code is using busy waits instead of semaphores. This could be improved, when the SPI is working.
=> SPI support for BK7231T (untested)

src/driver/drv_bl0937.c, src/driver/drv_bl0937.h, src/driver/drv_bl0942.c, src/driver/drv_bl0942.h, src/driver/drv_bl_shared.c, src/driver/drv_bl_shared.h, src/driver/drv_cse7766.c, src/driver/drv_cse7766.h, src/driver/drv_local.h, src/driver/drv_main.c, src/driver/drv_pwrCal.c, src/driver/drv_pwrCal.h, src/driver/drv_test_drivers.c, src/driver/drv_test_drivers.h
A lot of duplicated code for calibration of power/energy sensors could be removed.
Tested calibration for BL0942 and it is working.
=> Combined and outsourced energy calibration + Cleaned up headers/includes

src/driver/drv_bl_shared.c
Added following on http site (like in Tasmota):
- Apparent Power (Vrms * Irms)
- Reactive Power (Power that does no work in the load, but goes back into the grid)
- Power Factor (Active Power/Apparent Power)
- Energy Today
- Energy Yesterday
Tested and working.
=> Show more energy information on http site

.gitignore, src/sim/Shape.cpp, src/sim/Simulator.cpp, src/sim/sim_sdl.cpp
Changed window default size to 800x600
Window can be resized
Windows resize event to fix renderer size
Shape Drawinfoprmation SubShapes index fixed
=> Changed .gitIgnore to ignore build items and dependencies dlls and lib

src/mqtt/new_mqtt.c
fixes for bugs from [this comment](https://github.com/openshwprojects/OpenBK7231T_App/issues/810#issuecomment-1525941122)
- fixed tasmota tele/sensor sent additionally with tele/status
- ~~fixed tasmota topics sent with mqtt_broadcastInterval when flag 2 is enabled~~
plus
- tasmota topics sent on mqtt connect only when flag 10 is enabled
- fixed tasmota tele publish +1s from set interval
=> fixes for bugs from #810

src/cmnds/cmd_tokenizer.c
Add the possibility to put a mix of text and constants in MQTT topic or values
=> Update constant detections in MQTT

src/hal/ln882h/hal_wifi_ln882h.c
=> most other wifi functions and state change callbacks implemented

.github/workflows/workflow.yaml, .gitmodules, .releaserc.yaml, Makefile
Thread on forum: https://www.elektroda.com/rtvforum/viewtopic.php?p=20917847#20917847
=> Draft: OpenLN882H autobuild support

src/driver/drv_bl0937.c
Trying to make bl0937 work on BL602
=> Try add bl0937 for BL602

src/hal/bl602/hal_wifi_bl602.c
Adds RSSI for BL602, looks ok, reports similar to what BK7231N reports in the same place
=> Implement RSSI for BL602 (#5)

src/httpserver/rest_interface.c
Change to erasing flash in smaller chunks, this avoids issues with http connection, because erasing seems to stop everything.
Makes it faster usually too, finishes in 5.5 seconds. Tested by creating almost 800kb image and works without any issues.
There is a bug in http_rest_error function that it does not work correctly in bl602 and just resets connection, I will try to fix later.
=> Fix OTA for BL602

src/httpserver/http_fns.c
So if we are showing temperature now, it should be done properly with units, this fixes that.
Maybe we should move it to a driver?
=> Make temperature readable

src/httpserver/http_fns.c
Adds temperature to bl602 too. Seems not very stable unfortunately.
=> Add temperature to BL602

src/driver/drv_sm16703P.c
This is a workaround to the SPI sending in SM16703P to support SK6812 strips on BK7231N, e.g. the Action LSC Battletron Light Bar.
Discussion is in #1055.
=> Fix SM16703P SPI quirks

src/driver/drv_sm16703P.c
This adds some documentation comments to the changes from #1084, #1085.
=> Add some doc comments to drv_sm16703P

src/driver/drv_bmp280.c, src/driver/drv_doorSensorWithDeepSleep.c, src/driver/drv_ntp.c, src/driver/drv_pwm_groups.c, src/driver/drv_sm2235.c, src/driver/drv_tuyaMCU.c, src/httpclient/http_client.c, src/httpserver/json_interface.c, src/httpserver/rest_interface.c
Compiler warnings for OpenBK7231T_App build are fixed in that pull request.
=> Warnings in OpenBK7231T_App fixed.

src/driver/drv_ir.cpp, src/driver/drv_ir.h
* Migrate headers for SpoofIrSender to drv_ir.h (avoid issues between SpoofIrSender and IRSend object instantiation)
* Update code for SpoofIrSender to incorporate a pointer to myIRsend object which can be attached to SpoofIrSender instance
* Push functions through currently attached myIRsend instance for previously blank functions within SpoofIrSender
=> Updates to drv_ir.h and drv_ir.cpp

src/httpserver/http_fns.c, src/httpserver/new_http.c, src/httpserver/new_http.h, src/httpserver/rest_interface.c, src/logging/logging.c
Based on the suggestion from the issue #1002 I've added 'MAIN page' to the HTML footer. It's small change but in fact makes navigation through WebGUI more convenient.
=> MAIN page item added to the HTML footer.

src/driver/drv_sm16703P.c, src/driver/drv_tuyaMCU.c, src/driver/drv_uart.c, src/httpserver/json_interface.c, src/new_cfg.c, src/new_pins.c
Cleanup of compiler warnings present in Application.
=> App warnings cleanup - part2

src/hal/w800/hal_wifi_w800.c
This adds static ip support for W600 module
=> Add static ip for W600

src/user_main.c
=> Add watchdog for LN882

src/httpserver/new_http.c, src/logging/logging.c
This fixes crash on bl602 when unknow http method is sent, solves part of #1177, however still crashes somewhere else
=> Fix unknown method handling

src/cmnds/cmd_tokenizer.c
It was under platform define, should be fixed to proper define
=> allow bl602 to use constants in publishFloat ant similar

src/httpserver/http_fns.c
As requested here:
https://www.elektroda.com/rtvforum/topic4055720.html
=> simple addition to allow clear text passwords for WiFi

src/httpserver/hass.c, src/httpserver/hass.h, src/httpserver/http_fns.c
=> Publish IP and SSID to Home Assistant

src/cmnds/cmd_main.c
https://github.com/openshwprojects/OpenBK7231T_App/pull/1186
=> Update cmd_main.c - powersave description update

src/mqtt/new_mqtt.c
This makes use of asynchronous dns resolution in lwip, fixes issues with restarts if internet breaks. tested on bk7231n and bl602.
Fixes #1284. 
XR809 uses very old lwip so there is no way to ask for ipv4 ip, but it probably does not support ipv6 anyway, so should be no issue
=> Resolve MQTT DNS asynchronously

src/hal/ln882h/hal_pins_ln882h.c
Requires https://github.com/openshwprojects/OpenLN882H/pull/15
Needs further testing. I tested it only on 1 channel.
=> LN882H PWM

src/driver/drv_charts.c, src/driver/drv_test_charts.c, src/httpserver/http_fns.c
As https://github.com/openshwprojects/OpenBK7231T_App/pull/1360 but w/o changes to obk_config.h
=> nges to charts without changes to obk_config

Makefile, platforms/BK7231N/pre_build.sh, platforms/BK7231T/pre_build.sh, platforms/BL602/pre_build.sh, platforms/LN882H/pre_build.sh, platforms/W600/pre_build.sh, platforms/W800/pre_build.sh, platforms/XR809/pre_build.sh
Included a sample script for every platform to show it's working
=> Make changes to sdk from shell scripts just before start of build

src/hal/hal_adc.h, src/hal/w800/hal_adc_w800.c, src/user_main.c
=> Add internal chip temperature for W600 (untested) and W800

src/driver/drv_ds1820_simple.c
Reverted type change for W600
disable debug output by default
=> DS1820 fix type and small enhancement

src/driver/drv_tuyaMCU.c
Don't continue with the state machine if the device is in Open WiFi mode based on a user button press.
This avoids the device shutting down itself when in recovery mode. The MCU will reset the device after 90 seconds automatically.
Communicate to the MCU the device is in configuration mode. This will change the status LED blink pattern to reflect the state.
=> tuyaMCU: avoid state machine interfering with reset AP mode

src/cmnds/cmd_main.c
Apparently breaks connecting to wifi. Maybe something like ln882 should be done
=> Remove powersave for BL602
