openshwprojects/OpenBK7231T_App

- src/new_pins.c
PWM output was not getting past 10% in `Channel_OnChanged` (confirmed on Oscilloscope). Copied similar math operation from `PIN_SetPinRoleForPinIndex` function
> bugfix: correct pwm duty cycle

- src/httpserver/new_http.c
- src/new_builtin_devices.c
- src/new_pins.h
Add quick config for [Arlec CCT 9W Downlight](https://www.bunnings.com.au/arlec-grid-connect-smart-9w-cct-led-downlight_p0168694) using WB3L chip. Flashable via UART after simple disassembly of power supply box.
> feat: add quick config for CCT Downlight

- src/httpserver/new_http.c
Redirects the root `/` url to `/index` instead of showing `Not found`.
> feat: redirect root page / to /index page

- src/httpserver/rest_interface.c
- src/littlefs/lfs.c
- src/littlefs/lfs.h
- src/littlefs/lfs_util.c
- src/littlefs/lfs_util.h
- src/littlefs/our_lfs.c
- src/littlefs/our_lfs.h
- src/logging/logging.c
- src/logging/logging.h
- src/obk_config.h
- src/user_main.c
Add obk_config.h as a General build control include.
Start using obk_config.h to control inclusion of 'features'.
Littlefs seems a good fit if we want an FS on the device.
It sits in the OTA space, so will be wiped every OTA, but I'll do a 'staged OTA' where the FS is backed up, OTA done, then FS restored.
Having an FS with ~500K of space gives us a lot of opportunity, e.g. LUA/other scripting, serving static pages, etc. etc.
For the moment, LFS will do nothing (not even initialise).
You can initialise using /api/initlfs - that will format the area and write a  boot_count file.
If you call multiple times, you will see a log of boot_count increasing :). (it was just their sample... I'm not suggesting it as bootcount storage).
I will add get/post for filesystem manipulation, and serving of …
> Add littlefs (https://github.com/littlefs-project/littlefs)

- src/mqtt/new_mqtt.c
- src/new_pins.c
MQTT publish was only sending 0 or 1 even for PWM pins. Refactored `Channel_OnChanged` to still send 0/1 for relay & led pins but 0...100 for PWM enabled pins.
> fix: send pwm values (0...100) back via MQTT

- src/httpserver/new_http.c
- src/mqtt/new_mqtt.c
Uses library `will_topic` and `will_msg` to create a "Last Will and Testament" availability topic to enable Home Assistant (or other MQTT clients) to determine if the device is online or not. 
MQTT broker automatically sends `offline` when the client disconnects and added `online` publish on successful broker connection
> feat: add MQTT will and availability topic

- src/httpserver/http_tcp_server.c
- src/httpserver/new_http.c
- src/httpserver/new_http.h
- src/httpserver/rest_interface.c
- src/littlefs/lfs_util.h
- src/littlefs/our_lfs.c
- src/obk_config.h
- src/ota/ota.c
- src/user_main.c
Looking pretty good now....
lfs file endpoints - 
POST /api/lfs/folder/filename to write a file.  
GET /api/lfs/folder/filename to read/serve a file.
add reboot POST /api/reboot (3 second delay)
add OTA POST /api/ota (not used this yet, but below work well)
add fs backup GET /api/fsblock (reads as 512k file)
add fs flash POST /api/fsblock (writes the data your provide - should be a 512k little FS image)
Note: LittleFS blocks are at OTA + 0x1000 (so we don't write the header).
It's overwritten by OTA, hence the ability to backup and restore it.....
I still have random crashes/disconnects.  serial logs have some clues, so will try to 'catch it at it' and look into the logs.
Most likely we still have some thread conflict issues.
> Littlefs - more

- src/httpserver/new_http.c
- src/mqtt/new_mqtt.c
- src/mqtt/new_mqtt.h
- src/user_main.c
Adds ability to add callbacks to receive MQTT messages.
NOTE: I have not had time to test this this morning, but I thought you would like to see it..... (and maybe test?).
I think we should change the subscribed topic to be more TAS - 
e.g. cmnd/<basename>/<object>
Then we can subscribe to all cmnd/<base> without hearing stat/<base>/<object>
If/when we have scripting, this will be useful.  e.g. we can add the functionality to LUA to get relevant MQTT delivered direct to it, processed, and cause actions.  The specific topics can be requested directly from LUA....
br,
s
> MQTT updates

- src/flash_config/flash_vars.c
- src/flash_config/flash_vars.h
- src/flash_config/flash_vars_vars.c
- src/flash_config/flash_vars_vars.h
- src/httpserver/rest_interface.c
- src/logging/logging.c
- src/user_main.c
testing:
Read variables (causes read of flash)
http://192.168.1.176/api/testflashvarsa-0
increment bootcount:
http://192.168.1.176/api/testflashvars1-0
increment bootcount by 16:
http://192.168.1.176/api/testflashvars10-0
make bootsuccess equal bootcount.
http://192.168.1.176/api/testflashvars0-1
Result:
bootcount is incremented early in boot.
bootsuccess is set = bootcount after 30s.
if (bootcount - bootsuccess > 3), force AP mode at boot.
When in AP mode, leave booted for 30, and it will reset bootsuccess (so next boot will be normal).
Check what happens in WINDOWS and XR809 builds - they SHOULD ignore this code... (until you mod for XR809).
it MAY take an extra 8kbytes of RAM to simulate the flash mem on XR809...
Enjoy :).
> Flashvarstorage

- .github/workflows/workflow.yaml
- .gitmodules
- Makefile
Allows the Github Action to automatically update SDK submodules when upstream changes are detected and push changes back to this App repo in order to automatically track any changes to the SDKs `master` branches.
As requested by @openshwprojects in https://github.com/openshwprojects/OpenBK7231T_App/pull/45#issuecomment-1055930843
> feat: auto update SDK submodules

- src/httpserver/new_http.c
- src/httpserver/rest_interface.c
- src/littlefs/our_lfs.c
- src/logging/logging.c
- src/new_cmd.c
initialise g_commands (was this the issue?)
debug in exec.
fix a logging bug.
add commands: 
logtype direct|all - set direct to go direct to serial
logdelay <ms> - delay after log so we can see it before a crash? useful in debug.
exec not works as expected.  not sure why LFS was playing up.
> tune-ups & bugfixes

- .github/workflows/workflow.yaml
Changes the GH workflow to publish UG files (Tuya OTA format) as well. This is useful for users who want a quick n' easy download for a particular OpenBK7231 image to remotely OTA with the stock firmware.
> Publish UG artifacts in releases for stock OTA

- .releaserc.yaml
Sorry about that, made a mistake in the previous PR #70.
This one fixes it by adding a missing glob pattern for the releases step.
> fix(ci): Add missing glob pattern to releaserc for UG assets

- src/httpserver/http_fns.c
- src/mqtt/new_mqtt.c
- src/new_pins.c
- src/new_pins.h
- src/user_main.c
NOTE:
Builds, but untested.  Please review carefully.
The intent is that by causing three boot failures, (three times less than 30s up time), it goes into AP mode (as it did).  But now, when in AP mode, most configuration is skipped.  Pin config is loaded (so it can be changed), but h/w is not initialised.  mqtt is not initialised (no point in AP mode?), drivers not initialised, etc.
Pls check....
Pins: Separate actual pin h/w config from PIN_LoadFromFlash into new fn PIN_Setup(), so that we can load the pin config without setting it as active.
new variable g_enable_pins - if zero, no h/w config can be done.
new static var mqtt_initialised - set in mqtt_init, used to prevent mqtt__RunEverySecond if mqtt not initialised.
user_main.c - don't enable many functions if in AP mode.
> Modify startup when in AP mode.

- src/driver/drv_tuyaMCU.c
- src/driver/drv_tuyaMCU.h
- src/httpserver/http_fns.c
- src/new_pins.c
- src/new_pins.h
This PR adds suppport for moes WIFI Smart Dimmer Module 105 (WB2S).
* add a new channel type "dimmer", using same slider control as PWM
* maps TuyaMCU's dimming range to a normalized interval 0..100 (for web UI and MQTT)
* propagate new channel values to TuyaMCU (via TuyaMCU_OnChannelChanged)
* store TuyaMCU data point type for each mapped channel
moes WIFI Smart Dimmer Module 105 is controlled by two data points:
1: DP_TYPE_BOOL: on/off
2: DP_TYPE_VALUE: dimming level (0..1000)
autoexec.bat (working for me):
```
startDriver TuyaMCU
setChannelType 1 toggle
setChannelType 2 dimmer
tuyaMcu_setDimmerRange 0 1000
linkTuyaMCUOutputToChannel 1 1 1
linkTuyaMCUOutputToChannel 2 2 2
```
> add support for moes WIFI Smart Dimmer Module 105 (TuyaMCU dimmer, WB2S based)

- src/httpserver/http_fns.c
- src/new_builtin_devices.c
- src/new_pins.h
Adding new quick config for [RGB+CCT Arlec Downlight](https://www.bunnings.com.au/arlec-9w-grid-connect-smart-rgb-cct-led-downlight_p0168695).
Also updating my original CCT one to use channels 4 & 5 which seem to be the standard for colour temp mixing currently.
> feat: add template for Arlec RGB+CCT downlight

- .github/workflows/workflow.yaml
- .gitmodules
- .releaserc.yaml
- Makefile
Adding the new OpenW800 platform to the auto-build Github actions and releases.
As before, there's some SDK changes required too in https://github.com/openshwprojects/OpenW800/pull/1 to get this to work and once merged I can update the submodule back to `openshwprojects` repo.
One thing to note though is that each required source files need to be added to the OpenW800's `app/Makefile` similar to the `.project` file under the GUI IDE. Alternatively, we'd could add `#ifdef PLATFORM_W800` to all the `.c` files that aren't required for the W800 and recursively build all `.c` files if the list to exclude is much shorter.
> feat: add OpenW800 Platform

- .github/workflows/workflow.yaml
- .releaserc.yaml
Updated the automated release tooling to produce human-readable Release Notes for the GitHub releases with better change logs and a table explaining what each release asset is for (to the best of my knowledge at least). Also helps somewhat with https://github.com/openshwprojects/OpenBK7231T_App/issues/112.
Example in an alpha release on my dev repo here: https://github.com/talltechdude/OpenBK7231T_App/releases/tag/1.0.0-alpha.10
> feat: add release notes to Github releases

- src/httpserver/http_fns.c
This addresses #138 
* The HA config is generated in new style as per https://www.home-assistant.io/integrations/switch.mqtt/#new_format. 
* The light config also has some matching adjustment for `availability`.
Both switch and light have `unique_id` with the same value as the `name`.  `unique_id` allows the entity to be customized and one  would see something like this instead: ![image](https://user-images.githubusercontent.com/6459774/182364676-a36a1673-5a25-4840-aaeb-279a8c1573cb.png)
> Emit HomeAssistant config in new style

- src/hal/bk7231/hal_adc_bk7231.c
- src/hal/bk7231/hal_wifi_bk7231.c
- src/hal/bl602/hal_wifi_bl602.c
- src/hal/hal_wifi.h
- src/hal/w800/hal_adc_w800.c
- src/hal/w800/hal_wifi_w800.c
- src/hal/xr809/hal_adc_xr809.c
- src/hal/xr809/hal_wifi_xr809.c
- src/mqtt/new_mqtt.c
- src/obk_config.h
#104
This merge broadcasts the following values:
* host, mac, build: these are sent out once on startup
* datetime (if NTP driver is running), sockets, rssi, uptime, freeheap, ip: these get sent out every minute.
The values are similar to those broadcasted in Espurna. The ESP chip also provides internal voltage which is useful for battery based operations but I did not find any voltage level in the sdk.
Both sets of values are enabled by the `OBK_FLAG_MQTT_BROADCASTSELFSTATEPERMINUTE` flag.
I also fixed a few unused compile warnings due to unused variables.
> Public more device statuses via MQTT

- src/driver/drv_ntp.c
- src/new_cfg.c
- src/new_cfg.h
- src/new_pins.h
This request adds supports for custom NTP server in place of the default `217.147.223.78`. This allows NTP functionality to work even in firewalled devices.
* A new setting 20 char long has been created for this purpose.
* The new setting can be set using the command `ntp_setServer ipAddress`.
* Added another command `ntp_info` to view current NTP driver settings.
> Ntp config

- src/httpserver/http_fns.c
- src/httpserver/new_http.c
- src/httpserver/new_http.h
- src/httpserver/rest_interface.c
- src/logging/logging.c
First steps to HTML & JavaScript changes in the UI. I'd like to update things to be a bit easier to use, potentially more consistent with Tasmota. Starting small as I figure things out in the code.
* Made the links to repo, forum thread, donation open with target=_blank (in a new tab)
* Tweaked the UI to move all the status-information (state of devices, watchdog) together (this moves the shared UI items down a bit)
* Made it possible to just request the status information via http://url/index?state=
* Made the status-information section auto-updating with JavaScript every 3 seconds
* Moved forum thread & donation link to below main UI elements
* Moved auto-submit JS from separate script to inline with input elements
* Removes URL parameters from main page after the page loads with …
> Status information auto-updates, tweaked HTML, replaces #177

- BUILDING.md
Elaborate on necessary steps to make the build process easier for new users and contributors. The side note about whitespaces not being allowed on the Cygwin installation folder is because a python script somewhere in the build is not properly constructed, parsing paths with whitespaces as two separate arguments.
> Update BK7231T build info

- src/hal/bk7231/hal_wifi_bk7231.c
HAL_ConnectToWiFi() in src/hal/bk7231/hal_wifi_bk7231.c was added with some debug code enabled, which forced connection to a specific Wifi AP MAC address, rather than using the SSID information from the configs. I removed this block - now I can get it to connect normally. 
(I'm not quite sure how execution ends up - it was initially not a problem. I noticed it when syncing to the newer BK7231N SDK.)
> Remove old, breaking debug code in ConnectToWifi

- src/httpserver/new_http.c
@openshwprojects 
I pushed in a some fixes into to get Linux build working (https://github.com/iprak/OpenW600).  This request jut has a small fix to assign test USER_SW_VER. I also verified that the img can now be uploaded via direct ota. 
I am not sure what is the process to change build actions to build the firmware officially. But you might want to test the build on your device first.
> Defined USER_SW_VER

- src/cmnds/cmd_newLEDDriver.c
- src/driver/drv_bp1658cj.c
- src/driver/drv_bp1658cj.h
- src/driver/drv_bp5758d.c
- src/driver/drv_local.h
- src/driver/drv_main.c
- src/httpserver/new_http.c
- src/new_pins.h
- src/user_main.c
I recently bought a [Hama GU10 RGBCW 5,5W Lamp](https://www.hama.com/00176598/hama-wlan-led-lampe-gu10-5-5w-rgbw-dimmbar-refl-fuer-sprach-app-steuerung#article-details) , which incorporates the tuya [WBLC5](https://developer.tuya.com/en/docs/iot/wblc5-module-datasheet?id=K9duilns1f3gi) module and a BP1658(CJ) I2C LED driver IC (sadly no datasheet found) at P24 (DAT) and P26 (CLK). 
The delay from the BP5758 was a bit to slow for this chip, so I used 10 nops as a delay. Maybe it could be improved there.
> BP1658(CJ) support

- .gitignore
- src/hal/w800/hal_pins_w800.c
- src/httpserver/new_http.c
- src/httpserver/rest_interface.c
- src/new_pins.h
Fixes these things
* W800 configuration was allowing every pin to be PWM. Defined correct PWM pins for W600 and W800. There is no actual PWM implementation but at the least the pin choice would be correct now.
* Fixed PLATFORM_GPIO_MAX for W600.
I have now have my WiFi plug working and will soon submit a teardown.
> Fixed pins for W600 and W800

- src/cJSON/cJSON.c
- src/httpserver/hass.c
- src/httpserver/hass.h
- src/httpserver/http_fns.c
- src/logging/logging.c
- src/logging/logging.h
- src/new_common.h
- src/new_pins.h
Various fixes which were crippling W600 device.
* Fixed cJSON_Delete to nuke child nodes after they have been deleted.  cJSON_Delete recurses to clean up children but was not setting them to NULL. The caller (hass.c) was doing cleanup on child nodes in a NULL check and that caused crashes .. but only in W600.
* Defined constants for various configuration fields and converted discovery structure to use fixed size array based on those constants. This got rid of some malloc/free operations.
* Added logging for HASS.
* Discovery payload was always 1/0 and not the passed values which might be problem later.
This seems to resolve HASS discovery crashes on W600. The MQTT buffers in LWIP definitely helped as well.
> Hass discovery/Json memory fixes

- src/driver/drv_bp1658cj.c
- src/driver/drv_bp5758d.c
- src/new_common.h
I noticed that the 8 to 10 bit conversion is just a simple multiplication by 4. 
```c
cur_col_10[i] = rgbcw[g_channelOrder[i]] * 4;
```
I now added a simple linear mapping function to improve the 8 to 10 bit mapping:
```c
// Arduino mapping function
cur_col_10[i] = (rgbcw[g_channelOrder[i]] - 0x00) * (0x3FF - 0x00) / (0xFF - 0x00) + 0x00;
```
> added linear mapping function to map 0-255 to 0-1023

- src/cmnds/cmd_newLEDDriver.c
- src/httpserver/hass.c
- src/httpserver/hass.h
- src/httpserver/http_fns.c
- src/mqtt/new_mqtt.c
- src/mqtt/new_mqtt.h
- src/new_common.h
This is not done yet but I wanted to get feedback.
The discovery additions for RGB are based on `http_fn_ha_cfg`.
Changes
* Relay and PWM names now include `relay` or `light` to differentiate between them e.g. `w600CD2185A3 relay 1`. 
* RGB name does not need to include `index`. There should be only one RGB entity since that will only happen if all 5 PWMs were used or external driver was being used, right? 
* The hass config was appending 64 due to the relay loop before it. This has been fixed as well.
Issues
* Currently, PWM and relay have the same state_topic/command_topic (`w600Test/1/set`) which won't work. Instead, should it be  `w600Test/relay_1/set`? To avoid breaking existing settings, `w600Test/1/set` can still drive the relay.
* RGB: I think the topics are incorrect, shouldn't …
> Hass discovery support for  RGB

- src/httpserver/hass.c
This requests further reduces the mqtt message size. The current storage queue threshold is 768. Things won't crash if message is longer than that, the message just won't get sent out.
* HomeAssistant allows reduction of mqtt payload through the use of base topic (https://www.home-assistant.io/docs/mqtt/discovery/)
`A base topic ~ may be defined in the payload to conserve memory when the same topic base is used multiple times. In the value of configuration variables ending with _topic, ~ will be replaced with the base topic, if the ~ occurs at the beginning or end of the value.`
* And removed some spaces in the templates.
Here is the original payload of 697 bytes (formatted content):
```
{
"dev": {
"ids": [
"OpenW600_CD2185A3"
],
"name": "w600CD2185A3",
"sw": "1.0.0",
"mf": "WinnerMicro", …
```
> Hass discovery - use base topic

- src/logging/logging.c
bk_printf expects a formatting string, so if you pass it a log entry with a "%" in it, it will not show the "%" symbol and instead try to match a formatting pattern. This causes a difference in logging to serial vs logging to TCP / HTTP. Eg, this code results in different results on serial vs other logging:
```
ADDLOGF_INFO("At %d%%", 12);
```
Expected: Log shows "At 12%" - actual serial log is "At 12".
> Calls to bk_printf with logging strings need %s

- src/mqtt/new_mqtt.c
- src/new_cfg.c
This probably won't help with MQTT connection issues but helps with logging confusion.
* Cleaned up logging to avoid repeated malloc/free on `mqtt_status_message`. We were allocating that to 256 char so I defined it as 256 char array.
* Default mqtt host to be empty.
* Allocate sufficient space for a local variable.
I verified the empty host by doing a full erase which gave this logging
```
Info:MAIN:Time 16, free 30296, MQTT 0(0), bWifi 1, secondsWithNoPing 0, socks 2/8<CR>
Info:MQTT:mqtt_host empty, not starting mqtt<CR>
Info:MAIN:Time 17, free 30296, MQTT 0(1), bWifi 1, secondsWithNoPing 0, socks 2/8<CR>
```
> Mqtt logging cleanup

- BUILDING.md
Elaborate on necessary steps to make the build process easier for new users and contributors. It might be possible to build using Cygwin as well, but that fails on a missing `<sdk>/toolchain/riscv/CYGWIN` directory. Using Msys2, the `<sdk>/toolchain/riscv/MSYS` directory can be copied and renamed as described. This is probably something that should be changed in the SDK repo, but as far as the building information goes, this at least allows people to compile binaries without having to figure out these steps.
> Update BL602 build info

- .github/workflows/workflow.yaml
- .releaserc.yaml
- Makefile
Adding W600 build to automated build and releases
> feat: add W600 auto build

- .gitmodules
Here's a PR for migrating W600 SDK to the @openshwprojects fork if you wanted. Both repos are at same commit currently so no other changes should be required.
> feat: migrate W600 SDK

- src/mqtt/new_mqtt.c
- src/mqtt/new_mqtt.h
* Ensures that fields based on `CFG_GetMQTTClientId()` have more space than 64 which is what is the size of `mqtt_clientId`.
* Also added `MQTT_ready` for future use.
* Added MQTT failure reasons.
> Mqtt failure reason

- src/driver/drv_cse7766.c
Fixes for CSE7766 driver. I got my hands on one of the Deta Double GPOs with power monitoring similar to https://github.com/openshwprojects/OpenBK7231T_App/issues/109 so I can help with the further calibration/testing of this device and driver if required.
It looks like since https://github.com/openshwprojects/OpenBK7231T_App/commit/ce6f0aa37108b2c401c846ff876065c8acd98ff2 there are some divide by zeros happening (power usage shows as `inf`) and the calibration numbers aren't being returned from `VoltageSet` etc properly (and they are also large numbers now!). By backlog command now looks like this:
```
backlog startDriver CSE7766; VREF 383160; IREF 16520; PREF 10444800;
```
Calibrated @ 240V with 2400W / 10A resistive load.
> fix: cse divide by zero and calibration factors

- src/hal/w800/hal_main_w800.c
So this had been bothering me since I added support for W600 that the "Online for" did not seem to match the time the device had really be on. This shortcoming was more prominent after #276 where the "Online for" was updated on client and clearly did not match the value in "Info:MAIN".
1) We use g_secondsElapsed as a metric of how long the device has been running. This is not correct in W600 since the mainLoop has `tls_os_time_delay(1000);` and  `tls_os_time_delay` actually takes how many ticks to wait for. 
Based on code analysis, the same should hold true for W800. I unfortunately don't have W800 device yet.
2) We always wait for 1 second regardless of the time was spent in `Main_OnEverySecond`. I measured that Main_OnEverySecond takes about 5-6 ms when it does something like MQTT …
> W600 - Accounting for ticks (not the deer ticks)

- src/httpserver/http_fns.c
- src/httpserver/new_http.c
- src/httpserver/script_ha_discovery.js
* Fixed incorrect quit when device has only power measurement driver running and has no relay/PWM channels.
* Changed client script to show message sent from device,
> Discovery check power driver correctly

- src/driver/drv_main.c
- src/driver/drv_public.h
- src/httpserver/hass.c
* Added separate const for mqtt sensor class and units.
* Added missing units for voltage, current and power.
* Also added Wh unit for energy when device_class is not None.
https://github.com/openshwprojects/OpenBK7231T_App/issues/322
> HomeAssistant / Discovery / Add sensor units

- src/cmnds/cmd_main.c
- src/memory/memtest.c
- src/memory/memtest.h
they allow you to: 
- read the stack size & use.
- analyse ALL the heap area.
- wrap the native allocation routines to add guard areas before and after them, and detect overwrites of these (add 32 bytes to every malloc!!!)
- simple check of stack > percentage.
Implements 
__wrap_pvPortMalloc, __wrap_vPortFree
if wanted.
Enabled by:
// in the application.mk file add:
//  CFLAGS += -DOBK_HEAPGUARD=1
//  LFLAGS += -Wl,-wrap,pvPortMalloc -Wl,-wrap,vPortFree
//  LFLAGS += -Wl,-wrap,pvPortRealloc
// returns the size of a malloced pointer
// size will be the ALLOCATED size, not the REQUESTED size
// or -1 if unsupported platform.
// -2 if null
// -3 if ptr not in heap.
extern int getMallocSize(void *ptr);
// log the current stack use.
// supply name to say where you logged it.
// will log task …
> add memtest.c/.h

- src/httpserver/http_fns.c
Call `CFG_Save_IfThereArePendingChanges` to consistently save the settings in a few missing cases. `CFG_SetWebappRoot` always returns 1, so removed `else` block.
https://github.com/openshwprojects/OpenBK7231T_App/issues/380
> Save settings

- src/httpserver/rest_interface.c
- src/littlefs/our_lfs.c
- src/littlefs/our_lfs.h
- src/new_cfg.c
- src/new_cfg.h
- src/new_pins.h
- src/user_main.c
Breaking change as default is 0x8000 (16Kb…).
New commands:
lfssize - log size
lfssize 0x10000 - configure size
lfsunmount
lfsmount
lfsformat - reformat at current size
lfsformat 0x18000 - configure size and format lfs.
lfs size is stored in device config.
The main benefit of this is if a small LFS is used, it does not get overwritten when doing OTA. Also, if it DOES, you can still backup and restore, which will be faster with a smaller area. You still have the option for up to 0x80000 - 512 kbytes.
> Make LFS size adjustable.  

- src/httpserver/hass.c
- src/httpserver/http_fns.c
- src/mqtt/new_mqtt.c
This should help with https://github.com/openshwprojects/OpenBK7231T_App/issues/366.
Basically, the discovery data is correct but HomeAssistant doesn't know what to show unless we send something on those topics.  This was also mentioned briefly in https://github.com/openshwprojects/OpenBK7231T_App/issues/252#issuecomment-1272177253.
This merge
* Ensures that `PublishChannels` command is invoked for the same discovery topic. It was being sent before PWM channels. if the device is monitoring power, then power values are consistently sent over MQTT so I did not include that case.
* `MQTT_PublishOnlyDeviceChannelsIfPossible` has been adjusted to start channel publish from `PUBLISHITEM_SELF_DYNAMIC_LIGHTSTATE` instead of 0 thus accounting for PWM channels.
* …
> Publish channels at the end of discovery

- src/httpserver/hass.c
- src/httpserver/http_fns.c
This should resolve the color issue mentioned in https://github.com/openshwprojects/OpenBK7231T_App/issues/408
The rgb template is based on @openshwprojects comment here https://www.elektroda.com/rtvforum/topic3880540.html#20044837.
I tested it with 5 PWM setup and confirmed that it works with latest Hass.
> Fixed rgb template value

- src/cmnds/cmd_main.c
- src/cmnds/cmd_public.h
- src/logging/logging.c
- src/new_common.h
- src/user_main.c
Main_Init_Before_Delay() - things that can be done before IP is up. Main_Init_Delay() - actual startup delay, now on beken waits for extended app to finish, on other platforms is NO delay. Main_Init_After_Delay() - things that must wait until TCP/IP and other functions are available.
Q: what in platforms\bk7231t\bk7231t_os\beken378\func\func.c do we depend on?  e.g. which drivers can we start before it has finished?
> Split Main_Init into three.

- src/httpserver/rest_interface.c
- src/littlefs/our_lfs.h
- src/ota/ota.c
- src/ota/ota.h
- src/win_main.c
Fixes an issue in OTA where it could write beyond the end of the OTA space - especially when used to restore LFS.
Checks writing to flash in much more detail, limiting it to the area requested.
Checks response from init_ota() - so prohibiting multiple OTA writing at the same time.
Closes OTA correctly in the event of error.
> Otaprotect

- src/mqtt/new_mqtt.c
- src/mqtt/new_mqtt.h
If the mqtt client contains a '/', setChannel will fail to find the channel because it will stop at the first '/'.
This PR fixes setChannel to scan the client name instead, so it correctly skips over client. 
A new function `MQTT_RemoveClientFromTopic` is added, which skips over the topic.
In addition, the parsing in `channelSet` is greatly simplified, and and unnecessary copies are removed.
Fixes #515
> fix: setChannel should parse the client

- src/cmnds/cmd_newLEDDriver.c
As I've explained in this comment: https://github.com/openshwprojects/OpenBK7231T_App/issues/532#issuecomment-1345404174, the default initialization of `finalColor` and the failure of color interpolations in the alternate cw mode to take into account whether the light is enabled will cause the light to initially be turned on after boot.
I don't have a build environment set up so I haven't tested these changes, but they should fix #532.
> Fix startup and toggle issues with Smooth LED transitions flag

- src/cmnds/cmd_newLEDDriver.c
Make brightness exponential. Exponential mode can be set with command led_expoMode <0..4>:
0 = Off
1 = 1% min brightness with moderate exponential
2 = 1% min brightness with full exponential (default)
3 = 0.1% min brightness with moderate exponential
4 = 0.1% min brightness with full exponential
The mode can be set at startup by the "Change startup command text" Config command.
Modes 3 & 4 will not be very useful yet since minimum brightness is currently limited to 1%.
> Add Exponential Brightness

- src/new_pins.c
- src/user_main.c
goes with SDK mods to log powersave
Increases quicktick onterval to 25ms - 5ms interval completely prevents PS.
Note: you will NOT get PS without the logging changes....
> Powerlogging

- src/new_pins.c
- src/new_pins.h
- src/quicktick.h
- src/user_main.c
Call PIN_Ticks() from quicktick - so separating the functionality, but not changing anything.
This is mainly a cosmetic change - it does NOT change any functionality.
But it's in preparation for other changes - e.g. re-assessment of quicktick, running pins from interrupts, deep sleep...
And it provides functional separation....
> Move quicktick timer into user_main.c

- src/hal/bk7231/hal_main_bk7231.c
- src/new_pins.c
- src/quicktick.h
- src/user_main.c
Implementation of GPI interrupts on Beken.
You can enable them for testing by setting
#define BEKEN_PIN_GPI_INTERRUPTS
in quicktick.h
Also changes MQTT triggering to trigger a single read cycle even if multiple MQTT messages arrive before they are serviced.
NOTE THAT GPI Interrupts are currently NOT enabled in this PR.
But the functionality was previously tested on N, and I have subsequently ported on top of main, and tested the binaries with and without GPI ints enabled - but NOT *retested* actual button functionality!!!! (as I have no buttons...).
Why do we need this? - it goes towards Deep Sleep.  Even if we don't use the GPI interrupts, the features of gathering the pins and levels are needed for deep sleep waking from GPI.
> Prepare gpi interrupt

- src/cmnds/cmd_newLEDDriver.c
- src/driver/drv_bl0937.c
- src/driver/drv_main.c
- src/hal/hal_pins.h
- src/hal/w800/hal_pins_w800.c
- src/httpserver/http_fns.c
- src/mqtt/new_mqtt.c
- src/new_common.h
- src/new_pins.c
- src/obk_config.h
I redid the merge to avoid white space changes. As the project owner, at some point, you should make a decision to ensure consistent code with the goal of providing a better dev environment. That will promote more input into this project and also make it a joy to develop. The new simulation checks are in that direction. Unfortunately, formatting is a mess .. even on the same line. I tend to use VSCode because I can build directly without jumping into CygWin console and I like to make the code I touch consistent. This has been my experience with other Github project I have worked with.
But I completely understand the review effort for those unintentional formatting changes; I occasionally run into the same while reviewing changes from over enthusiastic developers :-)
====
This provides …
> W600: Basic driver support

- src/driver/drv_dht_internal.c
- src/hal/bk7231/hal_pins_bk7231.c
- src/hal/bl602/hal_pins_bl602.c
- src/hal/hal_pins.h
- src/hal/win32/hal_pins_win32.c
- src/hal/xr809/hal_pins_xr809.c
- src/logging/logging.h
- src/user_main.c
My first attempt was to use rising+falling edge interrupts which would avoid the need to continuously poll for pulse detection. But there is seem to no high (micro) resolution timer so was not able to identify the pulse.
Next I attempted to use native `tls_usleep` and `tls_msleep` for delay but that seemed to lock the chip... probably because the timer might be used elsewhere.
So finally fell back to adjusting the nop delay to suit W600.
The DHT source files are included in https://github.com/openshwprojects/OpenW600/pull/3 and has to be merged first. Please don't forget to update the submodules after that.
> Added DHT support in W600

- src/httpserver/rest_interface.c
Currently, webApp logs error if the chip is on older firmware or if the chip not supporting SSDP or if SSDP is not running.
This is because the webApp calls the end point `obkdevicelist` which is absent. We can handle this more gracefully in webApp by checking if the chip is currently supporting SSDP and that is what this PR does.
WebApp PR: https://github.com/OpenBekenIOT/webapp/pull/34
> Return supportsSSDP

- src/httpserver/hass.c
- src/httpserver/hass.h
- src/httpserver/http_fns.c
- src/new_pins.c
- src/new_pins.h
This change was motivated by a door/window sensor from Tuya, where I had to manually publish the discovery payload for the sensor (after converting to OpenBK) otherwise HASS would report the sensor as unavailable after a reboot or integration reload.
I had to change `get_Relay_PWM_Count`, and I found out it is also used by a Tasmota-related function, but that remains to be done as I have no idea how it would work to report or configure a binary sensor for Tasmota.
> Add support for binary sensor (digital input) in Home Assistant discovery

- src/httpserver/new_http.c
Replaces the web server base64 encoded shortcut icon with the same one almost 3 times smaller (264 bytes) in .gif format instead of the actual .png (748 bytes).
This is same size as [tasmota's .ico](https://github.com/arendst/Tasmota/blob/be988827487224e21a073799b1842e9f9f8f72a2/tasmota/html_uncompressed/HTTP_HEADER1_ES6.h#L6) format.
> Same shortcut icon 3 times smaller

- src/new_cfg.c
This is the main part of the fix for #553. It uses a separate statically allocated buffer for the key that is one byte larger than array in the on-flash config structure and places a terminating null byte at the end.
I have to admit that I don't know why there are os_* functions, but I guess they are supposed to be used since they exist.
This change depends on openshwprojects/OpenBK7231N#13 and openshwprojects/OpenBK7231T#18.
For BL602 the psk element in struct wifi_mgmr_connect_ind_stat_info is already 65 bytes long.
For XR809 the Doxygen comment of wlan_sta_set says that 64 digit hexadecimal keys are supported.
For W800 and W600 the disassembly of tls_wifi_connect shows that the function exits early if the key length is >= 65, so I assume 64 is ok.
> allow storage of WPA2 PSK as hexadecimal string

- src/cmnds/cmd_main.c
- src/cmnds/cmd_public.h
- src/user_main.c
While (test) powersave can be enabled via command, it is currently difficult to know if a device is in that mode. This PR appends the status to the status message.
> Added POWERSAVE status message

- .gitignore
- openBeken_win32_mvsc2017.vcxproj
- src/httpserver/http_tcp_server_nonblocking.c
- src/sim/Simulator.cpp
- src/sim/Simulator.h
- src/sim/sim_sdl.cpp
- src/win_main.c
By default the Win32 app runs on port 80 but it could be that 80 was already taken. I added an option to define `port=8080` in debugger command line options. The debugger command line options get saved into `openBeken_win32_mvsc2017.vcxproj.user` which should not be included in the repo. The argv params do get passed down to `glutInit` but I don't think that part should be impacted since we did not have any command line params to start with.
Also fixed the order of buttons which appear when Simulator is shutdown to be Yes/No/Cancel instead of Cancel/Yes/No.
> Win32 app / optional port

- README.md
- src/httpserver/http_fns.c
- src/new_pins.c
- src/new_pins.h
I have a [Feit Smart Dimmer](https://www.elektroda.com/rtvforum/topic3949246.html) which has a LED indicator on the front. Its brightness level in controllable. Options are off, dim, and bright. I have added a channel type to support this.
> Add OffDimBright channel type for LED indicator brightness.

- src/hal/w800/hal_wifi_w800.c
This goes with this PR (https://github.com/openshwprojects/OpenW600/pull/6) to not use oneshotconfig at all.
We are not seeing OTA issues in W800 so I decided to keep the overall changes limited to W600.
> Remove oneshotconfig

- .gitignore
- BUILDING.md
- docker/Dockerfile.BK7231x_build_env
- docker/Dockerfile.build_env
- docker/README.md
I wanted to build OpenBK7231T for my Mac, but the current build process doesn't support that. So I created this Dockerized build environment and documented the process for using it to build. This approach would be useful on all platforms including Windows and Linux to ensure that the build environment is consistent.
> Added a Dockerized build environment

- src/driver/drv_battery.c
- src/httpserver/new_http.c
- src/new_pins.c
- src/new_pins.h
- src/user_main.c
To provide Zero configuration for End User :
- 2 new pins BAT_ADC and BAT_Relay
- Autostart of driver if pins associated
- change vdivider default value to 2.29 Seems like default for 2AA battery sensor
> Changing behaviour of battery driver

- src/httpserver/http_fns.c
As a first time user I found the help text somewhat confusing. This is a suggestion to clarify things a bit.
* Dropped the reference to "textfield" as this is implementation specific. One day it could be one of those numeric up/down spinner controls. And I am not sure one can enter text value when index is expected to be numeric. Unless there's support to enter variables...
* Added a reference to the dropdown field, as this is what I see as "the first" field one needs to set. And it is a text value. The previous reference "first textfield" was actually referring to the second numeric field.
It would also be nice to link "role" to a documentation about what all these values mean. I could not find one. I don't know most of them and how are they used. I just took a guess.
tjk :)
> Clarification text for the pin mapping configuration.

- src/driver/drv_tuyaMCU.c
- src/user_main.c
I've got two S09 desktop thermometer / hygrometer / calendar + IR send/receiver devices .
On both I observed the same problem with frequent restarts of wifi every about 800s. 
I found that problem comes from MCU that resets WIFI module because it doesn't respond correctly on two commands  : 
0x2B - get network status 
0x24 - get RSSI 
after my changes they work fine and additionally RSSI is set automatically without adding commands to autoexec. 
Could you please take a look , check if it is correct or even check on other devices ex. TH06 .. 
ps. at the end one small fix for user_main.c
> Fix for frequent restarts of S09 device 

- docker/README.md
Adds instructions on how to build the OpenBeken software on Apple Silicon Macs. This solves the issues that the compilers used by OpenBeken are built for x86 platforms.
closes #732
> Added instructions for building with Docker on ARM Macs

- docker/README.md
Sorry, after you merged the last PR, I noticed there were a few typos int eh README. This fixes them.
> Docker ARM Macs README Typos

- src/driver/drv_pwrCal.c
Removed old unautomated methods for power calibration.
Saving 192 Byte of Flash
Tested and working
> Removed old unautomated methods for power calibration + Use Tokenizer to save Flash

- docker/Dockerfile
This PR enables a docker build on non-amd64 platforms.
Previously, the docker build would error out on other platforms because i386 architecture isn't available on these platforms, which would pull a non-amd64 image by default. This PR adds an explicit request for amd64 platform so the correct image gets built.
> feat: enable docker build on non amd64 platforms

- src/driver/drv_bridge_driver.c
- To add support for ZMAi-90 Smart Switch (with CBU Module) Bi-Stable relay.
Tested on ZMAi-90 with BridgePulseLength set to 5.
- Fix some typos
> Allow BridgePulseLength to set to lower values

- docker/Dockerfile
Changed `docker/Dockerfile` to use Ubuntu 20.04, fixes #809
> Fixed Docker to build using Ubuntu 20.04

- src/driver/drv_bl0937.c
- src/driver/drv_bl0942.c
- src/driver/drv_bl_shared.c
- src/driver/drv_bl_shared.h
- src/driver/drv_cse7766.c
- src/driver/drv_pwrCal.c
- src/driver/drv_pwrCal.h
- src/driver/drv_test_drivers.c
As mentioned before, the the BL0942 is now summing up the power for 800 ms, but we read out the power only every second. The IC has an build in energy counter. This commit makes use of the energy counter (read out energy) instead of calculating the energy from the power. This improves the precision.
Tested for both, UART and SPI device. For my devices the resolution of the energy is 0.18 Wh (UART) and 0.34 Wh (SPI). The precision depends on the circuit connected to the BL0942. I.e. it can be with current shunt (resistance value) and current coil (windings).
The energy counter of the IC is correlated to the power. Thus the energy counter uses the power calibration. No additional calibration is needed.
> BL0942: Increased precision by using IC energy

- src/cmnds/cmd_main.c
- src/debug_tuyaMCUsimulator.c
- src/driver/drv_bl0942.c
- src/driver/drv_cse7766.c
- src/driver/drv_tuyaMCU.c
- src/driver/drv_uart.c
- src/driver/drv_uart.h
- src/selftest/selftest_local.h
- src/sim/sim_local.h
- src/sim/sim_uart.c
- Fixed bugs in uart_driver which caused corrupted uart reads, when the ring buffer came to its "overflow".
- Renamed two functions to clearer names:
- UART_GetNextByte -> UART_GetByte (no index is moved to a "next" position)
- UART_AppendByteToCircularBuffer -> UART_AppendByteToReceiveRingBuffer (there is already UART_InitReceiveRingBuffer)
- Tested with BL0942, which produced checksum errors before the commit. After commit everything works fine, and no more checksum errors occur.
> Bugfixes in UART: No more corrupted packages

- bouffalo.mk
I changed sdk to not include aws jsmn which was being used instead of your jsmn (they are the same but it could lead to problems later). This means your app needs to include the functions.
> added src/jsmn since it is no longer pulled from sdk

- src/httpserver/hass.c
Otherwise, HA warns 'Last reset missing'
> Fix stat_class for energy sensor

- src/httpserver/http_fns.c
- src/httpserver/new_http.c
- src/httpserver/new_http.h
Not sure my adding a new http_getRawArg method is the best way to go about ignoring the initial "?" when parsing the data within the body of a POST request, but otherwise this does seem to fix #872 for me.
Fixes #872
> Respond to POSTs as well as GETs in /cm handler

- src/httpserver/hass.c
- src/httpserver/http_fns.c
The merge removes the CFG_GetShortDeviceName prefix to entityName to address #895. PWM entities just have "Light" as the name. The entity_id remains unchanged. Further customization of name/icon can be done in HomeAssistant.
This has been tested on 7231T and W600 switches. I don't have other devices.
It seems that just pushing HomeAssistant discovery is not sufficient to resolve the warning, a restart at Homeassistant end might be necessary.
> Remove duplicate prefix

- src/driver/drv_tuyaMCU.c
- src/new_pins.c
- src/new_pins.h
My energy meter with tuyaMCU exposes current and leakage current, so both Current_div100. When I linkTuyaMCUOutputToChannel RAW_TAC2121C_VCP it sets both channels.
I prefer to set only the first channel by RAW_TAC2121C_VCP but other "currents" can be set by different outputs.
> Set only first channel by type in VCP tuyaMCU

- src/driver/drv_cse7766.c
- src/driver/drv_pwrCal.c
- src/driver/drv_pwrCal.h
Recently I purchased DIN rail mountable energy monitor based on SCE7759B and CB2S. After testing with official release i spotted two issues: 
Current measured was showing as 0.0A and after attempt to calibrate with 100w bulb and measuring using my Rigol DM3058 it started showing as "nan". After compiling my own firmware I found the issue. When the real current was rounded to 0 because it was integer. This resulted in devision by zero during calculation of the calibration constant, and also lowering the percision of the instrument. Changing raw current to float fdixed the issue.
The other issue I have spotted is that some time there were chacksum errors because the packet start was mis identifyed, because 0x5A was appearing elswere in the packet. This was easily corrected with comparing …
> CSE77xx fix

- src/driver/drv_cht8305.c
Added support for the new SensyLink sendor CHT8310 and this should fix [ISSUE-983](https://github.com/openshwprojects/OpenBK7231T_App/issues/983)
I have the sensor and tested it. Compatibility with the old sensor shold be maintained, but I don't have it to test. Please confirm If you have the hardware to test, before merge. 
The new sensor has more features and the way to calculate measurement results is different. I put an if there depending on the sensor type. On the old one if can be confirmed reading a sensor ID from the IC. If it is not 8305, the code assumes it is the new one.  
I have utilised the low power mode of the IC where it only draws 50nA, and makes measurements on request. This is accomplished writing anything to the "Oneshot" register. If the sensor is the old one this is …
> Add cht8310 support

- .releaserc.yaml
- docker/Dockerfile
- docker/README.md
- docker/build_target_platforms.sh
Changes that was missed in [!1041](https://github.com/openshwprojects/OpenBK7231T_App/pull/1041).
Docker build tested locally for ln882h.
> LN882H: fix release upload, fix docker build

- src/httpserver/http_fns.c
This uses api from beken to get internal temperature. 
However in my plugs it reports ~270. Could it be Celsius * 10?
There is these defines and checks 
`#define ADC_TEMP_VAL_MIN                            (50)`
`#define ADC_TEMP_VAL_MAX                            (700)`
Seems strange for Celsius *10, so not sure
> Add internal temperature for Beken chipd

- src/driver/drv_sm16703P.c
This is adds code to support SK6812 strips which swap the red and green colors with respect to SM16703P.
The init command is enhanced to accept e.g. `SM16703P_Init 16 SK6812`. Allowed chip type strings are "SK6812", "sk6812", "GRB", "grb".
> Add SK6812 support to SM16703P driver

- src/driver/drv_ddp.c
This fixes an off-by-one memory corruption on received UDP frames in the DDP driver.
Received `nbytes` can be up to `sizeof(msgbuf)` thus `msgbuf[nbytes] = '\0'` will reliably crash the device on all UDP messages of 64 bytes or more.
Since we don't ever need the DDP message to be terminated I've just removed the offending line.
> Fix DDP off-by-one memory corruption

- src/driver/drv_max72xx_clock.c
- src/driver/drv_ntp_events.c
- src/httpserver/json_interface.c
After recent changes to fix usage of time_t, there were 4 other places, which should be addressed:
```
max@max:~/LN882H/20240326/OpenBK7231T_App$ find . -name "*.[ch]" | xargs grep -C 2 -n  "gmtime((time_t"
./src/driver/drv_max72xx_clock.c-71-
./src/driver/drv_max72xx_clock.c-72-	// NOTE: on windows, you need _USE_32BIT_TIME_T 
./src/driver/drv_max72xx_clock.c:73:	ltm = gmtime((time_t*)&g_ntpTime);
./src/driver/drv_max72xx_clock.c-74-
./src/driver/drv_max72xx_clock.c-75-	if (ltm == 0) {
--
./src/driver/drv_ntp_events.c-172-
./src/driver/drv_ntp_events.c-173-	// NOTE: on windows, you need _USE_32BIT_TIME_T 
./src/driver/drv_ntp_events.c:174:	ltm = gmtime((time_t*)&runTime);
./src/driver/drv_ntp_events.c-175-	
./src/driver/drv_ntp_events.c-176-	if (ltm == 0) {
-- …
```
> Some more fixes to usage of gmtime

- src/driver/drv_ssdp.c
- src/hal/bl602/hal_wifi_bl602.c
This adds ability to use static ip for BL602 devices as requested in #1116
> Add static ip for bl602

- src/driver/drv_freeze.c
So that it does not stop watchdog timer from working on BL602. Maybe RunFrame disables interrupts somewhere?
> Make freeze less aggresive

- src/user_main.c
This adds watchdog for the W600 chip. Tested with freeze driver, reboots as expected with watchdog, and freezes without.
> Add watchdog for W600

- src/hal/w800/hal_wifi_w800.c
Looks like rrsi needs to be adjusted W600, like in examples. Tested, looks similar to beken in similar places
> Fix RSSI for W600

- bouffalo.mk
- src/cmnds/cmd_main.c
- src/httpserver/rest_interface.c
- src/littlefs/lfs_util.h
- src/littlefs/our_lfs.c
- src/littlefs/our_lfs.h
- src/new_common.h
- src/obk_config.h
- src/user_main.c
This adds LittleFS  support for BL602 as requested in #1117 
It is using media partition, which is defined in partition layout, but unused. Offsets are currently static, so only supports layout from BLDevCube 1.4.8. 
Scripts also work.
> Add LittleFS for BL602

- src/hal/w800/hal_wifi_w800.c
This fixes incorrect printing on network settings for W600. 
Caused by incorrect call to wm_vsnprintf. It can't be called as normal function. va_args need to setup and so on. So using regular snprintf instead
> fix network data log

- src/httpserver/http_fns.c
Index page takes 2 seconds to refresh LN882H, due to rssi being called twice.
Calling it once makes performance normal for some reason
> Fix index page performance for LN882H

- src/driver/drv_ntp.c
- src/win_main_scriptOnly.c
This makes date consistent everywhere, because now it's two different ways on front page.
yyyy/mm/dd is very odd format, with slashes it's usually mm/dd/yyyy. But I like to use ISO time.
> Use ISO date everywhere

- src/cmnds/cmd_main.c
- src/user_main.c
A slight improvement (I hope) to PR #1143
Since for me using "ln_pm_sleep_mode_set(LIGHT_SLEEP)" makes metering with  BL0937 unusable, I suggest simply using PowerSave with a number > 1 to enable this (making it possible to decide, which level of PowerSave is wanted).
Since bOn is allready an int, its just one cahnge to set the bool value g_powersave not to bOn but to the bool value of bOn.
Then its possible to set sleep mode if PowerSave has a value > 1.
A word of warning:
PoweSave on LN882H will not work as a startup command.
Using "PowerSave 1" just seems to have no effect.
But using "PowerSave 2" as autostart command prevents the device from connecting to your WiFi network!
So please only use  "PowerSave 2" as a user command!
> LN882H enable or disable sleep mode while using a PowerSave

- src/hal/ln882h/hal_wifi_ln882h.c
This should make ln882h appear with proper openLN882h hostaname instead of ln_sta.
Needs SDK fixes here https://github.com/openshwprojects/OpenLN882H/pull/13
Can't test because there is no guide to compile locally.
> Set DNS hostname for ln882h

- src/httpserver/json_interface.c
strftime takes a lot of space and we only use simple number printing from it. 
Saves 7kb space for ln882h, w600, and 20kb(!) for bl602
> Remove strftime to save space

- src/httpserver/hass.c
- src/httpserver/hass.h
- src/httpserver/http_fns.c
- src/mqtt/new_mqtt.c
- src/mqtt/new_mqtt.h
Requested here https://github.com/openshwprojects/OpenBK7231T_App/issues/1188 and I also think it's useful to have even if not accurate
> Publish internal temperature to Home Assistant

- src/cmnds/cmd_tokenizer.c
This fixes constants in publishFloat for LN882H and publishInt for BL602 and LN882H
> Use functional define for constant expansion

- src/cmnds/cmd_main.c
- src/cmnds/cmd_tokenizer.c
I wondered why echo would never expand expressions like "$ch10" but return the string as is (e.g.: "Info:CMD:$ch10").
I think it was just a typo, for "Tokenizer_GetArgFrom(0)" would just return g_argsFrom[0] and not expanding content like "Tokenizer_GetArg(0)".
And since we forced a single argument, this should be correct, I hope.
At least, it now works for me ;-)
> let echo return expanded arguments

- src/httpserver/http_fns.c
Just implemented and checked this, and it works properly for me.
```
[1/28] SSID: RT-GPON-7B3C, Channel: 11, Signal -86
.....
[28/28] SSID: OnyxFish, Channel: 1, Signal -55
```
> BL602: WiFi AP Scan

- src/driver/drv_ds1820_simple.c
As requested in PR #1294:
- added CRC calculation to verify OW readings
- changed "usleepds" to multiples of "usleep()" for BEKEN and LN882H
- introduced an information about "age" of reading on Main Page (since bad readings are ignored, temperature might be "older")
> Add CRC to simple DS18x20 driver

- src/httpserver/new_http.c
Reason for the Change:
The current text "Build on xxxxx" is grammatically incorrect in this context. The word "build" is a verb in its base form, which is used to describe the action of constructing or creating something. However, in the context of displaying the date and time when the program was constructed, the past participle "built" should be used. This is because we are referring to an action that has been completed in the past.
> Change "Build" to "Built" in the build date text

- src/httpserver/json_interface.c
Requesting "STATUS" or "STATUS 5" on W800 was crashing the module. Reason was "tmpStr" was too short, now it works.
Might have caused instability on other platforms, too
> Fix W800 crashing on "STATUS" request - fixed json_interface.c

- src/user_main.c
For me especially W800 often fails to authenticate to WiFi on the first try.  
Having to wait for 1 minute is very long, especially if you are trying some new versions and have to wait often.
So my proposal is to reduce this to 5 seconds during the first 30 seconds after startup.
> Allow faster WIFI connect retries during first seconds after startup

- src/driver/drv_cht8305.c
- src/driver/drv_cht83xx.h
Added humidity to alert configuration.
On driver init, will read status register and log what triggered the alert. (https://github.com/NonPIayerCharacter/OpenBK7231T_App/blob/7c5fd07de0011c88eb8293b7ad91987b2ecda2ee/src/driver/drv_cht8305.c#L257)
Update docs, taken from #1302
> CHT831X alert add humidity

- Makefile
Update Makefile for W800:
Download toolchain only once
- after downloading and extracting create a file
- check for presence of this file before downloading and extracting again
> Speeding up consecutive builds for W800

- src/httpserver/http_fns.c
ATM a Dimmer channel is visible on the main page without showing, to which channel it belongs:
This PR adds the label - I did not use the way like PWN for this (with "\<h5>") leads to a bigger gap between label and slider than just inserting the text and a linebreak:
> Add channel label to dimmer

- src/hal/w800/hal_wifi_w800.c
> Beautify/fix networking info of W800

- docker/Dockerfile
- docker/README.md
Hi,
When I tried to compile OpenBeken with docker locally, I had the same issue as #767 .
This was due to the UID of user used by the docker container. The UID was 1000 in docker and not the one of my Host user.
To correct this, I added the current UID as an argument to build the container image.
> Add UID of user when building to avoid permission issue

- src/cmnds/cmd_tokenizer.c
- src/hal/ln882h/hal_wifi_ln882h.c
- src/httpserver/http_fns.c
- src/new_common.h
Enable static IP for LN882H
Needs a change in SDK - in 
[sdk/OpenLN882H/components/net/lwip-2.1.3/src/port/ln_osal/netif/ethernetif.c b/components/net/lwip-2.1.3/src/port/ln_osal/netif/ethernetif.c](url)
to make sure, DHCP isn't called after we set the IP. Simple approach: If we set an IP in STA mod, don't start DHCP:
```
diff --git a/components/net/lwip-2.1.3/src/port/ln_osal/netif/ethernetif.c b/components/net/lwip-2.1.3/src/port/ln_osal/netif/ethernetif.c
index e2b485e..2884ef3 100644
--- a/components/net/lwip-2.1.3/src/port/ln_osal/netif/ethernetif.c
+++ b/components/net/lwip-2.1.3/src/port/ln_osal/netif/ethernetif.c
@@ -16,6 +16,7 @@
#define IF_NAME_STA "ST" // Only support two ascii characters
#define IF_NAME_AP  "AP" // Only support two ascii characters
+static int STA_USE_DHCP = …
```
> LN882H - static ip

- src/driver/drv_ddp.c
The DDP_Parse() function should write the incoming DDP data to the LEDs. But it did it twice per incoming packet. First with LED_SetFinalRGB() which set all LEDs to a single color(?) and then again with SM16703P_setMultiplePixel() to the correct values. Resulting in flickering LEDs.
This fixes that and writes the pixels with either the SM16703P function OR the other one.
fixes https://github.com/openshwprojects/OpenBK7231T_App/issues/1325
> fix flicker in DDP (fixes #1325)

- platforms/LN882H/CMakeLists.txt
- platforms/W600/Makefile
- platforms/W800/Makefile
- platforms/XR809/Makefile
Actually for three platforms (LN882H, XR809 and W800) you need to change (C)Makefiles if you want to add new sources.
Theese Makefiles reside inside SDK, so you need to make changes to sdks for this, too
This PR suggests to change the sdk makefiles (once more) to be later able to do changes without altering sdk
Added a folder "platforms", with content for LN882H, XR809 and W800
for as far as I know, adding source files will be included by default
with the other platforms
I will add the corresponding PRs for OpenW800, OpenLN882H and OpenXR809:
https://github.com/openshwprojects/OpenW800/pull/10
https://github.com/openshwprojects/OpenLN882H/pull/18
https://github.com/openshwprojects/OpenXR809/pull/7
Added for W600:
https://github.com/openshwprojects/OpenW600/pull/11
> Change to let sdk makefile include actual versions from within app repository

- src/driver/drv_ds1820_simple.c
New features:
* Handle all types of DS1820 tempature sensors by detecting the family of the sensor and calculating the temperature accordingly
* Clean up some log prints
* Set the channel value with current temperature
* Update the reading every second instead of every 15s
> Improve DS1820 driver

- .github/workflows/workflow.yaml
Update workflow.yaml try fix (sometimes) missing windows binaries by adding "build2" as "needs" for release
> Fix release sometimes missing windows binaries

- src/httpserver/hass.c
A few fixes for HASS MQTT for Energy
- unit_of_meas was set twice
- skip stat_cla measurement for timestamp
`HASS Log:  energy_clear_date (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; `
- skip unit_of_meas if empty - if unit is not set (drv_bl_shared.c @ "power_factor") mqtt unit_of_meas was set as empty string
`HASS Log:  sensor...power_factor is using native unit of measurement '' which is not a valid unit for the device class ('power_factor') it is using; expected one of ['no unit of measurement', '%']; `
> A few fixes for HASS MQTT for Energy

- README.md
- src/httpserver/hass.c
Home assistant auto discovery did only work correctly for value dividers of 1, 10, 100, ...
Functionality for divider of 2 has been implemented but disabled later-on (by mistake?)
In my case (BHT-002 climate control with TuyaMCU), using this small fix, it is now working correctly
> Fix bug preventing divider of 2 to work properly for home assistant auto discovery

- src/httpserver/hass.c
There was a typo in the Mqtt Discovery patch for HASS, so power, current (and others) were missing stat_cla in the json.
https://github.com/openshwprojects/OpenBK7231T_App/pull/1398
> HASS MQTT patch typo

- src/driver/drv_uart.c
- src/driver/drv_uart.h
- fix for incorrectly reported size of UART_GetDataSize when Ring Buffer overflows
- fix for reading UART buffer - when Ring Buffer overflows we now always have the last (g_recvBufSize - 1) bytes to read
> UART RingBuffer overflow and reported size fix

- src/httpserver/http_fns.c
- src/new_pins.c
- src/new_pins.h
- src/user_main.c
I have added new commands to allow preserve the last used SSID. The last used SSID is stored in the retained channel. By default, the feature is disabled.
To enable this feature, the channel that will be used to store the last SSID must be set using the setStartupSSIDChannel command in early.bat. The recommended value is 7, values 8-12 are already used for LED brightness and so on.
It has to be in early.bat. Autoexec.bat is processed after the wifi data is loaded.
To disable this feature, set setStartupSSIDChannel -1
There is also a setStartupSSID command that will force the SSID to be used on the next reboot. 0=SSID1, 1=SSID2.
[early.bat]
setStartupSSIDChannel 7
> Ssid2 retain mod - last used SSID will be preserved /Beken Only/

- src/libraries/Arduino-IRremote-mod/src/IRSend.hpp
- src/libraries/Arduino-IRremote-mod/src/IRremoteInt.h
- src/libraries/Arduino-IRremote-mod/src/ir_NEC.hpp
Hi, just wanted to share my workaround code for sending IR codes in 48-NEC1 protocol:
http://www.hifi-remote.com/johnsfine/DecodeIR.html#48-NEC1
The  Arduino-IRremote-mod doesn't support it natively, so I patched it in. The library supports sending RAW or pronto codes, but I think OpenBeken has a limited payload, so it will not fit.
The result is this example command:
**IRSend NEC-1-0303-0-30**
you need to specify **bit length!** (in hex: 0x30=48 bits)
and the 16bit aCommand is has 2 fields:
- command/function in the highByte (mask: 0xFF00)
- E value in lowByte (mask: 0x00FF)
I tested it with my FAN controllable with IR remote, it works nicely
> Added 48-NEC1 support to the Arduino-IRremote-mod

- src/httpserver/new_http.c
- src/httpserver/new_http.h
- src/httpserver/rest_interface.c
I've slightly edited some lfs http handlers so that it will correctly respond with text/css mimetype for .css files.
> feat(httpserver): improved mimetype handling for js, css

- src/driver/drv_pwrCal.c
You can set 0 or NAN as calibration constant currently, which should not be allowed, and in my case bricks the device.
Should be validated correctly. 
Should fix #1502
> Fix calibration

- src/driver/drv_sm16703P.c
A bit of "DRY" that also fixes an issue when DDP controlled LED strips have a non standard color order
see https://github.com/openshwprojects/OpenBK7231T_App/issues/1491
> Refactor multi pixel setting logic in SM16703P driver

- src/driver/drv_bl_shared.c
- src/mqtt/new_mqtt.c
- src/mqtt/new_mqtt.h
This fixes mqtt disconnects for me. I thinkk publishing energy data with Qos 0 is appropriate because it's transient, and updates any few seconds anyway. Fixes #1512
> Publish energy mqtt data with qos zero

- src/driver/drv_bl0937.c
value = pulses / time
More pulses for same time - bigger value.
More time for same pulses count - smaller value.
Twice more pulses for twice time - same value.
ticksElapased * tick_period == elapsed time in ms
ticksElapased * tick_period / 1000 == elapsed time in s
final = final * expected_time / elapsed_time; //expected time is 1 second.
final = final * expected_ticks / elapsed_ticks; //expected ticks for 1 second: (1000.0ms / portTICK_PERIOD_MS)
Closes: #1270
> BL0937: Fixed swapped division and multiplication in measured value correction

- src/cmnds/cmd_script.c
- src/user_main.c
This fixes multi-line command for BL602 issue #1523 . Problem is that realloc is not working on BL602. So by moving malloc for g_scrbuffer to the function where it's used realloc is not required and so everything works. (except it would fail if single script line is more than 256 chars long, but that problem exists already and should not be stopping this fix)
I think realloc is broken on BL602 because malloc and free is redefined in aos_freertos.c file, while realloc is not, so the one libc is used and obviously you can't mix those two. I need to check maybe new sdk fixed realloc.
> Fix multi-line startup command for BL602

- src/driver/drv_ds1820_simple.c
- src/driver/drv_ds1820_simple.h
1) Fixed incorrect first reading - 85.00C (issue #1571)
2) Fixed variables reset on driver restart
3) Implemented DS1820_SetResolution command
4) Done refactoring of DS1820_OnEverySecond()
Example `of DS1820_SetResolution`:
```
Info:SENSOR:DS1820[23] - Starting conversion
Debug:SENSOR:DS1820[23] - family=28, raw=3752, cfg=60 (12 bit resolution)
Info:SENSOR:DS1820[23] - Temp=29.31
Info:SENSOR:DS1820[23] - Starting conversion
Debug:API:POST to api/cmnd
Debug:CMD:cmd [DS1820_SetResolution 10]
Info:CMD:[WebApp Cmd 'DS1820_SetResolution 10' Result] OK
Info:SENSOR:DS1820[23] - Starting conversion
Debug:SENSOR:DS1820[23] - family=28, raw=3776, cfg=20 (10 bit resolution)
Info:SENSOR:DS1820[23] - Temp=29.50
Debug:API:POST to api/cmnd
Debug:CMD:cmd [DS1820_SetResolution 12]
Info:CMD:[WebApp Cmd …
```
> DS1820: Fixes and style improvement

- src/cmnds/cmd_tasmota.c
Added json command to make OpenBeken firmware to be compatible with SmartThings Tasmota Edge Driver
[Tasmota Command Documents](https://tasmota.github.io/docs/Commands/#control)
[Smart Things Tasmota Edge Driver](https://community.smartthings.com/t/st-edge-tasmota-edge-for-sonoff-tuya-many-other-esp-wifi-http-devices-over-2000-tasmota-supported-devices/241493)
> added Tasmota command json to get compatibility with SmartThings Tasmota Edge Driver

- src/httpserver/hass.c
HASS - Sensor name 'Battery' also for BATTERY_CHANNEL_SENSOR
Designed for battery-powered temperature sensors with TuyaMCU, where this is used:
```
setChannelType 3 BatteryLevelPercent
linkTuyaMCUOutputToChannel 3 val 3 0 50
```
Changes HASS discovery name from:
to
> HASS - Sensor name 'Battery' also for BATTERY_CHANNEL_SENSOR

- src/driver/drv_tuyaMCU.c
When using the tuyaMcu_sendCmd command without data - for example for heartbeat, a random byte was sent in the data.
`const char *s=Tokenizer_GetArg(1);`
Tokenizer_GetArg() returns 0 if the parameter is missing, and (s) was not tested, but only (*s)
tuyaMcu_sendCmd 0x00 
data sent before bugfix: 55 EA 00 00 00 01 DB DB  - BAD 
data sent aftrer bugfix:  55 EA 00 00 00 00 FF  - OK
> tuyaMcu_sendCmd without second param bugfix

- src/driver/drv_bl_shared.c
Bugfix: in ENABLE_BL_TWIN mode, energy_today for channel B was not reset if both channels were used in parallel.
> ENABLE_BL_TWIN mode - reset energy_today also for channel B

- src/driver/drv_tuyaMCU.c
Replace magic values present in the code with the more descriptive macros.
As these macros are redundant with the comments, drop the repsective comments.
> tuyaMCU: replace network state magic values

- src/driver/drv_tuyaMCU.c
This place expected -1 for "unmapped", but -999 can come from this line: https://github.com/openshwprojects/OpenBK7231T_App/blob/fe51ee8f47237e13062cb0df9ab95ad6867ef987/src/driver/drv_tuyaMCU.c#L883
This was detected with ASAN (#1651), the error message:
```
=================================================================
==2532658==ERROR: AddressSanitizer: global-buffer-overflow on address 0x5642389c5e37 at pc 0x564237e67492 bp 0x7fff17726e50 sp 0x7fff17726e40
READ of size 1 at 0x5642389c5e37 thread T0
#0 0x564237e67491 in CHANNEL_GetType src/new_cfg.c:427
#1 0x564237dfc933 in TuyaMCU_ApplyMapping src/driver/drv_tuyaMCU.c:1126
#2 0x564237dff92f in TuyaMCU_ParseStateMessage src/driver/drv_tuyaMCU.c:1632
#3 0x564237e019fa in TuyaMCU_ProcessIncoming src/driver/drv_tuyaMCU.c:1977
#4 …
```
> Fix out-of-bounds access on g_cfg.pins.channelTypes

- .github/workflows/workflow.yaml
- custom.mk
- platforms/linux/ubsan.suppressions
Undefined Behavior Sanitizer (UBSAN) [1] is a similar tool to ASAN, useful for catching bugs related to undefined behavior.
All the problems it detects seem related to the bitshifts related to flags. Here's a sample:
```
src/new_pins.c:2437:8: runtime error: left shift of 1 by 31 places cannot be represented in type 'int'
#0 0x55a1b51011c1 in PIN_get_Relay_PWM_Count src/new_pins.c:2437
#1 0x55a1b500389b in NewLED_InitCommands src/cmnds/cmd_newLEDDriver.c:1627
#2 0x55a1b5150208 in Main_Init_BeforeDelay_Unsafe src/user_main.c:1151
#3 0x55a1b51506e7 in Main_Init_Before_Delay src/user_main.c:1290
#4 0x55a1b5150a05 in Main_Init src/user_main.c:1428
#5 0x55a1b515902c in SIM_ClearOBK src/win_main.c:166
#6 0x55a1b515a0fd in main src/win_main.c:534
#7 0x7f1acfdabd8f in __libc_start_call_main …
```
> Run linux tests with UBSAN

- src/new_pins.c
Actually, CHANNEL_IsInUse() will report all channel values. Change to only report used channels up to PIN_IOR_NofChan() for this role
> CHANNEL_IsInUse() report only used channels

- src/driver/drv_tuyaMCU.c
- src/driver/drv_tuyaMCU.h
I have resolved your issue by implementing a new feature that prevents the BK7231T from automatically sending commands to the TuyaMCU during boot, which previously overwrote the TuyaMCU’s saved state.
1. **New flag:** `g_tuyaMCU_allowAutomaticSending` – prevents automatic command sending during initialization/boot.
2. **New function:** `TuyaMCU_EnableAutomaticSending(bool enable)` – allows toggling automatic sending on or off.
3. **New command:** `tuyaMcu_enableAutoSend [0/1]` – can be used in the console or in your autoexec.bat to control this behavior.
4. **Modified LED function:** `TuyaMCU_OnRGBCWChange()` – now checks the flag before sending any commands to the TuyaMCU.
- **Default behavior:** Automatic sending is disabled at boot (`g_tuyaMCU_allowAutomaticSending = false`).
- …
> Tuya mcu automatic sending

- .github/workflows/workflow.yaml
- src/driver/drv_ds1820_full.c
- src/driver/drv_ds1820_full.h
- src/driver/drv_main.c
- src/httpserver/json_interface.c
As pointed out in #1804 , DS1820 sensors are missing in status.
This PR will add the output for "simple" 
and "full" driver:
> Add DS1820 to JSON sensor output

- src/driver/drv_ds1820_full.c
Change JSON output for multiple DS18x20 to be more Tasmota compliant.
Last commit is "plain" Tasmota:
The one before additionally adds "Name" to display the name given for the sensor
> change JSON for multiple DS18B20

- src/user_main.c
> Increase stack size for ESP8266

- src/httpserver/json_interface.c
Sensor name is chip as defined in PLATFORM_MCU_NAME
> Add Chip internal temperature as sensor in JSON

- src/cmnds/cmd_newLEDDriver.c
- src/selftest/selftest_http_led.c
The previous version of the gamma correction function didn't correct the gamma of the individual color channels, instead it was correcting the gamma only on the overall brightness.
This new algorithm, which borrows some logic from the ESPHome gamma implementation, resolves this and now colors on the bulbs match the selected colors.
> Fix gamma correction
